version: '3.8'

services:
  water_meter:
    container_name: frontend_licznik
    build:
      context: frontend_licznik/.
      dockerfile: Dockerfile
    volumes:
      - './frontend_licznik/.:/app'
      - '/app/node_modules'
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  mobile_app:
    container_name: frontend
    build:
      context: frontend/.
      dockerfile: Dockerfile
    volumes:
      - './frontend/.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    command: flask run
    volumes:
      - .:/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=flask_dev
volumes:
  postgres_data: