version: '3.8'

services:
#  water_meter:
#    container_name: water_meter
#    build:
#      context: water_meter/.
#      dockerfile: Dockerfile
#    volumes:
#      - '.:/app'
#      - '/app/node_modules'
#    ports:
#      - 3002:3002
  mobile_app:
    container_name: frontend
    build:
      context: frontend/.
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3001
  backend:
    build: backend/.
    command: flask run
    volumes:
      - .:/src/app/
    ports:
      - 5000:5000
    env_file:
      - backend/.env.dev
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=flask_dev
volumes:
  postgres_data: