"""init migration

Revision ID: 71daf981b327
Revises: 
Create Date: 2020-11-28 08:30:57.086170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71daf981b327'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('flat_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_table('alert',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=200), nullable=True),
    sa.Column('event_start', sa.DateTime(), nullable=True),
    sa.Column('leak_detection', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_table('event',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_start', sa.DateTime(), nullable=True),
    sa.Column('event_duration', sa.Interval(), nullable=True),
    sa.Column('flow', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_ud', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('group',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('group_description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('group_users',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=580), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('group_users')
    op.drop_table('group')
    op.drop_table('events')
    op.drop_table('event')
    op.drop_table('alert')
    op.drop_table('address')
    # ### end Alembic commands ###
